service: gdg-joegon
frameworkVersion: "2 || 3"

provider:
  # Stack settings
  name: aws
  stage: ${opt:stage, "dev"}
  region: ${opt:region, "ap-southeast-1"}
  profile: bot-steve
  deploymentMethod: direct
  deploymentBucket:
    name: gdg-joegon-sls-deployment

custom:
  dev:
    stageDashPrefix: dev-

# [WARNING] Remember to delete stack when off work! Charge per hour!
resources:
  Resources:
    AosJoegon:
      Type: AWS::OpenSearchService::Domain
      Properties:
        DomainName: aos-${self:custom.${sls:stage}.stageDashPrefix}joegon
        EngineVersion: OpenSearch_2.9
        ClusterConfig:
          InstanceType: t3.small.search
          InstanceCount: 1
          DedicatedMasterEnabled: false
          WarmEnabled: false
          MultiAZWithStandbyEnabled: false
          ZoneAwarenessEnabled: false
        EBSOptions:
          EBSEnabled: true
          VolumeType: gp3
          VolumeSize: 10
        AccessPolicies:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                AWS: ${aws:accountId}
              Action:
                - es:*
              Resource:
                - arn:aws:es:${aws:region}:${aws:accountId}:domain/aos-${self:custom.${sls:stage}.stageDashPrefix}joegon/*
